import React, { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { api } from '../api';
import styles from './QuoteExport.module.css';

export default function QuoteExport({ quote, settings = {}, totals = null }) {
  const ref = useRef(null);
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    if (!ref.current) return;
    setExporting(true);
    try {
      const canvas = await html2canvas(ref.current, {
        useCORS: true,
        allowTaint: false,
        scale: 2,
        backgroundColor: '#ffffff'
      });
      const link = document.createElement('a');
      link.download = `${quote.name.replace(/[^a-z0-9]/gi, '_')}_quote.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (e) {
      console.error('Export failed:', e);
      alert('Export failed: ' + e.message);
    } finally {
      setExporting(false);
    }
  };

  const date = quote.event_date
    ? new Date(quote.event_date + 'T00:00:00').toLocaleDateString()
    : null;

  const companyName = settings.company_name || '';
  const companyEmail = settings.company_email || '';
  const showTotals = totals && totals.subtotal > 0;

  return (
    <div className={styles.wrapper}>
      <button
        className="btn btn-primary"
        onClick={handleExport}
        disabled={exporting}
      >
        {exporting ? <><span className="spinner" /> Exporting…</> : '📷 Export as PNG'}
      </button>

      {/* Hidden render target */}
      <div className={styles.exportTarget} ref={ref}>
        <div className={styles.exportHeader}>
          {companyName && (
            <div className={styles.companyInfo}>
              <span className={styles.companyName}>{companyName}</span>
              {companyEmail && <span className={styles.companyEmail}>{companyEmail}</span>}
            </div>
          )}
          <h1 className={styles.exportTitle}>{quote.name}</h1>
          <div className={styles.exportMeta}>
            {date && <span>📅 {date}</span>}
            {quote.guest_count > 0 && <span>👥 {quote.guest_count} guests</span>}
          </div>
          {quote.notes && <p className={styles.exportNotes}>{quote.notes}</p>}
        </div>

        <div className={styles.exportGrid}>
          {(quote.items || []).map(item => (
            <div key={item.qitem_id} className={styles.exportItem}>
              <div className={styles.exportImgWrapper}>
                {item.photo_url ? (
                  <img
                    src={api.proxyImageUrl(item.photo_url)}
                    alt={item.title}
                    className={styles.exportImg}
                    crossOrigin="anonymous"
                    onError={e => { e.target.src = '/placeholder.png'; }}
                  />
                ) : (
                  <img src="/placeholder.png" alt="" className={styles.exportImg} aria-hidden />
                )}
              </div>
              <div className={styles.exportItemBody}>
                <span className={styles.exportItemTitle}>
                  {item.label || item.title}
                </span>
                {item.quantity > 1 && (
                  <span className={styles.exportQty}>×{item.quantity}</span>
                )}
              </div>
              {item.unit_price > 0 && (
                <div className={styles.exportItemPrice}>
                  ${(item.unit_price * item.quantity).toFixed(2)}
                </div>
              )}
            </div>
          ))}
        </div>

        {showTotals && (
          <div className={styles.exportTotals}>
            <div className={styles.exportTotalsRow}>
              <span>Subtotal</span>
              <span>${totals.subtotal.toFixed(2)}</span>
            </div>
            {totals.rate > 0 && (
              <div className={styles.exportTotalsRow}>
                <span>Tax ({totals.rate}%)</span>
                <span>${totals.tax.toFixed(2)}</span>
              </div>
            )}
            {totals.rate > 0 && (
              <div className={`${styles.exportTotalsRow} ${styles.exportTotalsTotal}`}>
                <span>Total</span>
                <span>${totals.total.toFixed(2)}</span>
              </div>
            )}
          </div>
        )}

        <div className={styles.exportFooter}>
          Generated by BadShuffle
        </div>
      </div>
    </div>
  );
}
