const { ITEM_MIGRATION_VERSION, ITEM_TABLE_STATEMENTS, ITEM_COLUMN_STATEMENTS } = require('./migrations/items');
const { USER_MIGRATION_VERSION, USER_TABLE_STATEMENTS, USER_COLUMN_STATEMENTS } = require('./migrations/users');
const {
  QUOTE_MIGRATION_VERSION,
  QUOTE_TABLE_STATEMENTS,
  QUOTE_COLUMN_STATEMENTS,
  QUOTE_POST_STATEMENTS,
} = require('./migrations/quotes');
const { LEAD_MIGRATION_VERSION, LEAD_TABLE_STATEMENTS, LEAD_COLUMN_STATEMENTS } = require('./migrations/leads');
const { FILE_MIGRATION_VERSION, FILE_TABLE_STATEMENTS, FILE_COLUMN_STATEMENTS } = require('./migrations/files');
const { MESSAGE_MIGRATION_VERSION, MESSAGE_TABLE_STATEMENTS, MESSAGE_COLUMN_STATEMENTS } = require('./migrations/messages');
const { ORG_MIGRATION_VERSION, ORG_TABLE_STATEMENTS, ORG_COLUMN_STATEMENTS } = require('./migrations/orgs');
const { runStatements } = require('./helpers');

const TABLE_CREATION_STATEMENTS = [
  ...ITEM_TABLE_STATEMENTS,
  ...USER_TABLE_STATEMENTS,
  ...FILE_TABLE_STATEMENTS,
  ...LEAD_TABLE_STATEMENTS,
  ...MESSAGE_TABLE_STATEMENTS,
  ...QUOTE_TABLE_STATEMENTS,
  ...ORG_TABLE_STATEMENTS,
];

const COLUMN_MIGRATION_STATEMENTS = [
  ...ITEM_COLUMN_STATEMENTS,
  ...USER_COLUMN_STATEMENTS,
  ...FILE_COLUMN_STATEMENTS,
  ...LEAD_COLUMN_STATEMENTS,
  ...MESSAGE_COLUMN_STATEMENTS,
  ...QUOTE_COLUMN_STATEMENTS,
  ...ORG_COLUMN_STATEMENTS,
];

const POST_MIGRATION_STATEMENTS = [
  ...QUOTE_POST_STATEMENTS,
];

const MIGRATION_VERSIONS = {
  items: ITEM_MIGRATION_VERSION,
  users: USER_MIGRATION_VERSION,
  quotes: QUOTE_MIGRATION_VERSION,
  leads: LEAD_MIGRATION_VERSION,
  files: FILE_MIGRATION_VERSION,
  messages: MESSAGE_MIGRATION_VERSION,
  orgs: ORG_MIGRATION_VERSION,
};

function applyMigrations(db) {
  runStatements(db, TABLE_CREATION_STATEMENTS);
  runStatements(db, COLUMN_MIGRATION_STATEMENTS);
  runStatements(db, POST_MIGRATION_STATEMENTS);
}

module.exports = {
  applyMigrations,
  MIGRATION_VERSIONS,
};
